version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  begin-pipeline:
    jobs:
    - path-filtering/filter:
        base-revision: main
        config-path: .circleci/pipeline.yml
        mapping: |
          \.circleci/.* build-all true
          .*\.go build-all true
          pkg/assets/.* build-docs true
    branches:
      only: main